---
# ====================================================================================
# FIREWALL - UFW
# roles/zabbix-agent-linux-in/tasks/firewall/ufw.yml
# ====================================================================================

# Instala o firewall UFW (Uncomplicated Firewall) para gerenciar regras de firewall.
- name: UFW | Instalando o UFW
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

# Coleta status atual do UFW, independente da distribuição e idioma.
- name: UFW | Coletando status
  ansible.builtin.command: ufw status verbose
  environment:
    LANG: C
    LC_ALL: C
  register: ufw_status
  changed_when: false

# Coleta informações com base no status, indicando se o UFW está ativo ou não.
- name: UFW | Definindo status ativo
  ansible.builtin.set_fact:
    ufw_active: >-
      {{
        'Status: active' in ufw_status.stdout.lower()
        or
        'Status: ativo' in ufw_status.stdout.lower()
      }}

# Libera SSH para garantir acesso remoto.
- name: UFW | Liberando porta 22 (SSH)
  community.general.ufw:
    rule: allow
    port: "{{ ufw_ssh_port }}"
    proto: tcp
  
# Libera porta 10050.
- name: UFW | Liberando porta 10050 (zabbix-agent)
  community.general.ufw:
    rule: allow
    port: "{{ zabbix_agent_port }}"
    proto: tcp