---
# ====================================================================================
# FIREWALL
# roles/zabbix-agent-linux-rm/tasks/firewall.yml
# ====================================================================================

# Valida o backend de firewall detectado para garantir que seja um dos suportados 
# (ufw, firewalld ou iptables) antes de tentar importar as tasks específicas do backend. 
# Isso ajuda a evitar erros de execução caso o backend detectado seja desconhecido ou não 
# suportado.
- name: FIREWALL | Validando backend de firewall
  ansible.builtin.assert:
    that:
      - firewall_backend in ['ufw', 'firewalld', 'iptables']
    fail_msg: "Backend de firewall não suportado: {{ firewall_backend }}"
    success_msg: "Backend detectado: {{ firewall_backend }}"
  when:
    - zabbix_agent_manage_firewall
  tags:
    - zbx-agt-rm-firewall
    - zbx-agt-rm-ufw
    - zbx-agt-rm-firewalld
    - zbx-agt-rm-iptables

# Inclui as tasks específicas do backend de firewall detectado para remover as regras 
# de firewall relacionadas ao Zabbix Agent, garantindo que as regras sejam removidas 
# corretamente de acordo com o firewall em uso no sistema.
- name: FIREWALL | Removendo regras para IPTables
  ansible.builtin.include_tasks:
    file: firewall/iptables.yml
  when: 
    - firewall_backend == "iptables"
    - >
      'all' in ansible_run_tags or
      'zbx-agt-rm-iptables' in ansible_run_tags or
      'zbx-agt-rm-firewall' in ansible_run_tags
  tags:
    - zbx-agt-rm-iptables
    - zbx-agt-rm-firewall

- name: FIREWALL | Removendo regras para Firewalld
  ansible.builtin.include_tasks:
    file: firewall/firewalld.yml
  when:
    - firewall_backend == "firewalld"
    - >
      'all' in ansible_run_tags or
      'zbx-agt-rm-firewalld' in ansible_run_tags or
      'zbx-agt-rm-firewall' in ansible_run_tags
  tags:
    - zbx-agt-rm-firewalld
    - zbx-agt-rm-firewall

- name: FIREWALL | Removendo regras para UFW
  ansible.builtin.include_tasks:
    file: firewall/ufw.yml
  when:
    - firewall_backend == "ufw"
    - >
      'all' in ansible_run_tags or
      'zbx-agt-rm-ufw' in ansible_run_tags or
      'zbx-agt-rm-firewall' in ansible_run_tags
  tags:
    - zbx-agt-rm-ufw
    - zbx-agt-rm-firewall